In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [9]:
print("Question a)")
adjacencyArray = [[0,1,1,1,1,0,0,0,0,0,0,0],[1,0,0,0,0,1,0,0,0,0,0,0],[1,0,0,0,0,0,1,0,0,0,0,0],[1,0,0,0,0,0,0,1,0,0,0,0],
                    [1,0,0,0,0,0,0,0,1,0,0,0],[0,1,0,0,0,0,0,0,0,0,0,0],[0,0,1,0,0,0,0,0,0,1,0,0],[0,0,0,1,0,0,0,0,0,0,1,0],
                    [0,0,0,0,1,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0,0,0,0,0],[0,0,0,0,0,0,0,1,0,0,0,0],[0,0,0,0,0,0,0,0,1,0,0,0]]
print("Adjacency Matrix A = \n", adjacencyArray)

Question a)
Adjacency Matrix A = 
 [[0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]


In [10]:
print("Question b)")
#get adjacency matrix
adjacencyMatrix = np.matrix(adjacencyArray)

#degree matrix
degree = np.zeros(len(adjacencyMatrix))
rowsum = adjacencyMatrix.sum(axis=1)

# loop through matrix and add up all degree connections
for j in range(0, len(adjacencyMatrix)):
    degree[j] = rowsum[j,0]
#print(degree)
# get the diagonal entries to correct the for loop oversumming
A = adjacencyMatrix.diagonal()
d = A.flat
diagMat = list(d)

#get degree matrix
degreeMatrix = np.diag(degree - diagMat)
print("Degree matrix = \n", degreeMatrix)

Question b)
Degree matrix = 
 [[4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:
print("Question c)")
#getting laplacian matrix
laplacianMatrix = degreeMatrix - adjacencyMatrix

print("laplacian matrix = \n", laplacianMatrix)

Question c)
laplacian matrix = 
 [[ 4. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [-1.  0.  2.  0.  0.  0. -1.  0.  0.  0.  0.  0.]
 [-1.  0.  0.  2.  0.  0.  0. -1.  0.  0.  0.  0.]
 [-1.  0.  0.  0.  2.  0.  0.  0. -1.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  2.  0.  0. -1.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  2.  0.  0. -1.  0.]
 [ 0.  0.  0.  0. -1.  0.  0.  0.  2.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  1.]]


In [12]:
x = [1,0,0,0,0,0,0,0,0,0,0,0]

In [13]:
print("Question d)")
print("L * x =",np.matmul(laplacianMatrix,x))
print("L * L * x =",x * np.matmul(laplacianMatrix,laplacianMatrix))
print("L * L * L * x =",x * laplacianMatrix * laplacianMatrix * laplacianMatrix)

Question d)
L * x = [[ 4. -1. -1. -1. -1.  0.  0.  0.  0.  0.  0.  0.]]
L * L * x = [[20. -6. -6. -6. -6.  1.  1.  1.  1.  0.  0.  0.]]
L * L * L * x = [[104. -33. -33. -33. -33.   7.   8.   8.   8.  -1.  -1.  -1.]]
